Clientes =
DISTINCTCOUNT(FactCustomerSnapshot[customer_id])

Clientes activos =
CALCULATE([Clientes], FactCustomerSnapshot[customer_status] = "Activo")

Clientes en riesgo =
CALCULATE([Clientes], FactCustomerSnapshot[customer_status] = "En riesgo")

Clientes churn =
CALCULATE([Clientes], FactCustomerSnapshot[churn_flag] = 1)

Tasa de churn =
DIVIDE([Clientes churn], [Clientes])

Clientes recurrentes =
CALCULATE([Clientes], FactCustomerSnapshot[repeat_customer_flag] = 1)

Tasa de recompra =
DIVIDE([Clientes recurrentes], [Clientes])

Pedidos =
DISTINCTCOUNT(FactOrders[order_id])

Unidades vendidas =
SUM(FactOrderItems[quantity])

Facturación neta =
SUM(FactOrders[net_revenue_usd])

Margen bruto =
SUM(FactOrders[gross_margin_usd])

Margen % =
DIVIDE([Margen bruto], [Facturación neta])

Ticket promedio =
DIVIDE([Facturación neta], [Pedidos])

CLV realizado promedio =
AVERAGE(FactCustomerSnapshot[net_revenue_usd])

Ingreso anual en riesgo =
SUM(FactCustomerSnapshot[annual_revenue_at_risk_usd])

Días desde última compra =
AVERAGE(FactCustomerSnapshot[days_since_last_order])

Devoluciones =
DISTINCTCOUNT(FactReturns[return_id])

Tasa de devolución =
DIVIDE(SUM(FactOrderItems[returned_quantity]), [Unidades vendidas])

Tickets de soporte =
DISTINCTCOUNT(FactSupport[ticket_id])

Churn mensual =
DIVIDE(
    SUM(FactMonthlyKPI[churned_customers]),
    SUM(FactMonthlyKPI[active_customers])
)

Facturación mes anterior =
CALCULATE([Facturación neta], DATEADD(DimDate[date], -1, MONTH))

Variación mensual facturación % =
DIVIDE([Facturación neta] - [Facturación mes anterior], [Facturación mes anterior])
